# Generated by Django 2.0.4 on 2018-11-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu_item_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_id', models.IntegerField()),
                ('restaurant_id', models.IntegerField()),
                ('restaurant_name', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(max_length=200)),
                ('energy_kcal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cholesterol', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'menu_item_list',
                'managed': False,
            },
        ),
    ]
